#include "configs.h"

int VISUAL_MODE_CURSOR_STEP_X = 5;
int VISUAL_MODE_CURSOR_STEP_Y = 10;
int VISUAL_MODE_CURSOR_WIDTH = 8;
int VISUAL_MODE_CURSOR_HEIGHT = 18;
char *VISUAL_MODE_CURSOR_BACKGROUND_COLOR = "rgba(38, 107, 255, .3)";
int NORMAL_MODE_SCROLL_DISTANCE = 32;
