#ifndef CONFIG_H
#define CONFIG_H

extern int VISUAL_MODE_CURSOR_STEP_X;
extern int VISUAL_MODE_CURSOR_STEP_Y;
extern int VISUAL_MODE_CURSOR_WIDTH;
extern int VISUAL_MODE_CURSOR_HEIGHT;
extern char *VISUAL_MODE_CURSOR_BACKGROUND_COLOR;
extern int NORMAL_MODE_SCROLL_DISTANCE;

#endif // !CONFIG_H
